// Supabase & Cloudinary Configuration for Vishista Office Solutions CMS

const SUPABASE_URL = 'https://oseccrcffoyttjgpazrt.supabase.co';
const SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9zZWNjcmNmZm95dHRqZ3BhenJ0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODc3NTM4OTEsImV4cCI6MjEwMzMyOTg5MX0.ESJ0iK2zcCPZZCZtfeYW7uObbEP7JxXUYJiSi9a4pzA';

const CLOUDINARY_CLOUD_NAME = 'iw4ntmv5';
const CLOUDINARY_UPLOAD_PRESET = 'ml_default';

// Embedded Seed Data Dataset for Fail-Safe CMS Resolution
const VISHISTA_SEED_DATA = {
  "categories": [
    {
      "name": "Workstations",
      "slug": "workstations",
      "description": "Height adjustable sit-stand desks, linear open-plan desking, and acoustic panel partitions",
      "image_url": "images/categories/cat_workstations.jpg",
      "display_order": 1,
      "is_visible": true,
      "is_published": true
    },
    {
      "name": "Tables",
      "slug": "tables",
      "description": "Executive director desks, boardroom meeting tables, cafe counters, and training desks",
      "image_url": "images/categories/cat_tables.png",
      "display_order": 2,
      "is_visible": true,
      "is_published": true
    },
    {
      "name": "Storage",
      "slug": "storage",
      "description": "Prelam credenzas, steel filing cabinets, high-density mobile compactors, and employee lockers",
      "image_url": "images/categories/cat_storage.png",
      "display_order": 3,
      "is_visible": true,
      "is_published": true
    },
    {
      "name": "Seating",
      "slug": "seating",
      "description": "High-performance mesh chairs, executive leather armchairs, training chairs, and cafe seating",
      "image_url": "images/categories/cat_seating.jpg",
      "display_order": 4,
      "is_visible": true,
      "is_published": true
    },
    {
      "name": "Soft Seating",
      "slug": "soft-seating",
      "description": "Executive leather couches, modular lounge sofas, collaborative booths, and pouffes",
      "image_url": "images/categories/cat_soft_seating.jpg",
      "display_order": 5,
      "is_visible": true,
      "is_published": true
    },
    {
      "name": "Pods",
      "slug": "pods",
      "description": "Solo phone booths and soundproof acoustic meeting pods",
      "image_url": "images/categories/cat_pods.jpg",
      "display_order": 6,
      "is_visible": true,
      "is_published": true
    },
    {
      "name": "Carpets",
      "slug": "carpets",
      "description": "Acoustic modular carpet tiles in contemporary geometric patterns",
      "image_url": "images/categories/cat_carpets.jpg",
      "display_order": 7,
      "is_visible": true,
      "is_published": true
    },
    {
      "name": "Outdoor",
      "slug": "outdoor",
      "description": "Synthetic wicker terrace seating, patio umbrellas, and garden breakout sets",
      "image_url": "images/categories/cat_outdoor.jpg",
      "display_order": 8,
      "is_visible": true,
      "is_published": true
    },
    {
      "name": "Educational",
      "slug": "educational",
      "description": "Student classroom desks, library reading carrels, hostel bunk beds, and auditorium chairs",
      "image_url": "images/categories/cat_education.png",
      "display_order": 9,
      "is_visible": true,
      "is_published": true
    }
  ],
  "subcategories": [
    {
      "name": "Height Adjustable Series",
      "slug": "height-adjustable-series",
      "category_slug": "workstations",
      "display_order": 1
    },
    {
      "name": "Desking Series",
      "slug": "desking-series",
      "category_slug": "workstations",
      "display_order": 2
    },
    {
      "name": "Panel Series",
      "slug": "panel-series",
      "category_slug": "workstations",
      "display_order": 3
    },
    {
      "name": "Cabin Tables",
      "slug": "cabin-tables",
      "category_slug": "tables",
      "display_order": 1
    },
    {
      "name": "Meeting Tables",
      "slug": "meeting-tables",
      "category_slug": "tables",
      "display_order": 2
    },
    {
      "name": "Cafe Tables",
      "slug": "cafe-tables",
      "category_slug": "tables",
      "display_order": 3
    },
    {
      "name": "Training Tables",
      "slug": "training-tables",
      "category_slug": "tables",
      "display_order": 4
    },
    {
      "name": "Prelam Storage",
      "slug": "prelam-storage",
      "category_slug": "storage",
      "display_order": 1
    },
    {
      "name": "Metal Storage",
      "slug": "metal-storage",
      "category_slug": "storage",
      "display_order": 2
    },
    {
      "name": "Compactor Storage",
      "slug": "compactor-storage",
      "category_slug": "storage",
      "display_order": 3
    },
    {
      "name": "Locker",
      "slug": "locker",
      "category_slug": "storage",
      "display_order": 4
    },
    {
      "name": "Mesh Chair",
      "slug": "mesh-chair",
      "category_slug": "seating",
      "display_order": 1
    },
    {
      "name": "Leather Chair",
      "slug": "leather-chair",
      "category_slug": "seating",
      "display_order": 2
    },
    {
      "name": "Training Chair",
      "slug": "training-chair",
      "category_slug": "seating",
      "display_order": 3
    },
    {
      "name": "Cafe Chair",
      "slug": "cafe-chair",
      "category_slug": "seating",
      "display_order": 4
    },
    {
      "name": "Lounge",
      "slug": "lounge",
      "category_slug": "soft-seating",
      "display_order": 1
    },
    {
      "name": "Sofa",
      "slug": "sofa",
      "category_slug": "soft-seating",
      "display_order": 2
    },
    {
      "name": "Collaborative",
      "slug": "collaborative",
      "category_slug": "soft-seating",
      "display_order": 3
    },
    {
      "name": "Pouffe",
      "slug": "pouffe",
      "category_slug": "soft-seating",
      "display_order": 4
    },
    {
      "name": "Occasional Tables",
      "slug": "occasional-tables",
      "category_slug": "soft-seating",
      "display_order": 5
    },
    {
      "name": "Classroom",
      "slug": "classroom",
      "category_slug": "educational",
      "display_order": 1
    },
    {
      "name": "Library",
      "slug": "library",
      "category_slug": "educational",
      "display_order": 2
    },
    {
      "name": "Hostel",
      "slug": "hostel",
      "category_slug": "educational",
      "display_order": 3
    },
    {
      "name": "Auditorium",
      "slug": "auditorium",
      "category_slug": "educational",
      "display_order": 4
    }
  ],
  "products": [
    {
      "name": "Veloz Mesh Chair",
      "slug": "veloz-mesh-chair",
      "category_slug": "seating",
      "subcategory": "Mesh Chair",
      "description": "Veloz ergonomic office chair featuring synchro-tilt mechanism, breathable mesh back, adjustable lumbar support, and heavy-duty nylon base.",
      "specifications": "Synchro-tilt mechanism, Class-4 Gas Lift, Breathable Korean Mesh, Nylon/Diecast Base.",
      "main_image": "images/archlabs/pages/page_4.png",
      "price": null,
      "display_price": false,
      "enquiry_only": true,
      "is_visible": true,
      "is_published": true,
      "display_order": 1
    },
    {
      "name": "Feather Mesh Chair",
      "slug": "feather-mesh-chair",
      "category_slug": "seating",
      "subcategory": "Mesh Chair",
      "description": "Feather ergonomic office chair featuring synchro-tilt mechanism, breathable mesh back, adjustable lumbar support, and heavy-duty nylon base.",
      "specifications": "Synchro-tilt mechanism, Class-4 Gas Lift, Breathable Korean Mesh, Nylon/Diecast Base.",
      "main_image": "images/archlabs/pages/page_5.png",
      "price": null,
      "display_price": false,
      "enquiry_only": true,
      "is_visible": true,
      "is_published": true,
      "display_order": 2
    },
    {
      "name": "Eiffel Mesh Chair",
      "slug": "eiffel-mesh-chair",
      "category_slug": "seating",
      "subcategory": "Mesh Chair",
      "description": "Eiffel ergonomic office chair featuring synchro-tilt mechanism, breathable mesh back, adjustable lumbar support, and heavy-duty nylon base.",
      "specifications": "Synchro-tilt mechanism, Class-4 Gas Lift, Breathable Korean Mesh, Nylon/Diecast Base.",
      "main_image": "images/archlabs/pages/page_6.png",
      "price": null,
      "display_price": false,
      "enquiry_only": true,
      "is_visible": true,
      "is_published": true,
      "display_order": 3
    },
    {
      "name": "Mustang Mesh Chair",
      "slug": "mustang-mesh-chair",
      "category_slug": "seating",
      "subcategory": "Mesh Chair",
      "description": "Mustang ergonomic office chair featuring synchro-tilt mechanism, breathable mesh back, adjustable lumbar support, and heavy-duty nylon base.",
      "specifications": "Synchro-tilt mechanism, Class-4 Gas Lift, Breathable Korean Mesh, Nylon/Diecast Base.",
      "main_image": "images/archlabs/pages/page_7.png",
      "price": null,
      "display_price": false,
      "enquiry_only": true,
      "is_visible": true,
      "is_published": true,
      "display_order": 4
    },
    {
      "name": "Bravo Mesh Chair",
      "slug": "bravo-mesh-chair",
      "category_slug": "seating",
      "subcategory": "Mesh Chair",
      "description": "Bravo ergonomic office chair featuring synchro-tilt mechanism, breathable mesh back, adjustable lumbar support, and heavy-duty nylon base.",
      "specifications": "Synchro-tilt mechanism, Class-4 Gas Lift, Breathable Korean Mesh, Nylon/Diecast Base.",
      "main_image": "images/archlabs/pages/page_8.png",
      "price": null,
      "display_price": false,
      "enquiry_only": true,
      "is_visible": true,
      "is_published": true,
      "display_order": 5
    },
    {
      "name": "Polar Mesh Chair",
      "slug": "polar-mesh-chair",
      "category_slug": "seating",
      "subcategory": "Mesh Chair",
      "description": "Polar ergonomic office chair featuring synchro-tilt mechanism, breathable mesh back, adjustable lumbar support, and heavy-duty nylon base.",
      "specifications": "Synchro-tilt mechanism, Class-4 Gas Lift, Breathable Korean Mesh, Nylon/Diecast Base.",
      "main_image": "images/archlabs/pages/page_9.png",
      "price": null,
      "display_price": false,
      "enquiry_only": true,
      "is_visible": true,
      "is_published": true,
      "display_order": 6
    },
    {
      "name": "Glanza Mesh Chair",
      "slug": "glanza-mesh-chair",
      "category_slug": "seating",
      "subcategory": "Mesh Chair",
      "description": "Glanza ergonomic office chair featuring synchro-tilt mechanism, breathable mesh back, adjustable lumbar support, and heavy-duty nylon base.",
      "specifications": "Synchro-tilt mechanism, Class-4 Gas Lift, Breathable Korean Mesh, Nylon/Diecast Base.",
      "main_image": "images/archlabs/pages/page_10.png",
      "price": null,
      "display_price": false,
      "enquiry_only": true,
      "is_visible": true,
      "is_published": true,
      "display_order": 7
    },
    {
      "name": "Yaris Mesh Chair",
      "slug": "yaris-mesh-chair",
      "category_slug": "seating",
      "subcategory": "Mesh Chair",
      "description": "Yaris ergonomic office chair featuring synchro-tilt mechanism, breathable mesh back, adjustable lumbar support, and heavy-duty nylon base.",
      "specifications": "Synchro-tilt mechanism, Class-4 Gas Lift, Breathable Korean Mesh, Nylon/Diecast Base.",
      "main_image": "images/archlabs/pages/page_11.png",
      "price": null,
      "display_price": false,
      "enquiry_only": true,
      "is_visible": true,
      "is_published": true,
      "display_order": 8
    },
    {
      "name": "Quartz Mesh Chair",
      "slug": "quartz-mesh-chair",
      "category_slug": "seating",
      "subcategory": "Mesh Chair",
      "description": "Quartz ergonomic office chair featuring synchro-tilt mechanism, breathable mesh back, adjustable lumbar support, and heavy-duty nylon base.",
      "specifications": "Synchro-tilt mechanism, Class-4 Gas Lift, Breathable Korean Mesh, Nylon/Diecast Base.",
      "main_image": "images/archlabs/pages/page_12.png",
      "price": null,
      "display_price": false,
      "enquiry_only": true,
      "is_visible": true,
      "is_published": true,
      "display_order": 9
    },
    {
      "name": "Ditto Mesh Chair",
      "slug": "ditto-mesh-chair",
      "category_slug": "seating",
      "subcategory": "Mesh Chair",
      "description": "Ditto ergonomic office chair featuring synchro-tilt mechanism, breathable mesh back, adjustable lumbar support, and heavy-duty nylon base.",
      "specifications": "Synchro-tilt mechanism, Class-4 Gas Lift, Breathable Korean Mesh, Nylon/Diecast Base.",
      "main_image": "images/archlabs/pages/page_13.png",
      "price": null,
      "display_price": false,
      "enquiry_only": true,
      "is_visible": true,
      "is_published": true,
      "display_order": 10
    },
    {
      "name": "Velfire Mesh Chair",
      "slug": "velfire-mesh-chair",
      "category_slug": "seating",
      "subcategory": "Mesh Chair",
      "description": "Velfire ergonomic office chair featuring synchro-tilt mechanism, breathable mesh back, adjustable lumbar support, and heavy-duty nylon base.",
      "specifications": "Synchro-tilt mechanism, Class-4 Gas Lift, Breathable Korean Mesh, Nylon/Diecast Base.",
      "main_image": "images/archlabs/pages/page_14.png",
      "price": null,
      "display_price": false,
      "enquiry_only": true,
      "is_visible": true,
      "is_published": true,
      "display_order": 11
    },
    {
      "name": "Optimus Mesh Chair",
      "slug": "optimus-mesh-chair",
      "category_slug": "seating",
      "subcategory": "Mesh Chair",
      "description": "Optimus ergonomic office chair featuring synchro-tilt mechanism, breathable mesh back, adjustable lumbar support, and heavy-duty nylon base.",
      "specifications": "Synchro-tilt mechanism, Class-4 Gas Lift, Breathable Korean Mesh, Nylon/Diecast Base.",
      "main_image": "images/archlabs/pages/page_15.png",
      "price": null,
      "display_price": false,
      "enquiry_only": true,
      "is_visible": true,
      "is_published": true,
      "display_order": 12
    },
    {
      "name": "Zoom Mesh Chair",
      "slug": "zoom-mesh-chair",
      "category_slug": "seating",
      "subcategory": "Mesh Chair",
      "description": "Zoom ergonomic office chair featuring synchro-tilt mechanism, breathable mesh back, adjustable lumbar support, and heavy-duty nylon base.",
      "specifications": "Synchro-tilt mechanism, Class-4 Gas Lift, Breathable Korean Mesh, Nylon/Diecast Base.",
      "main_image": "images/archlabs/pages/page_16.png",
      "price": null,
      "display_price": false,
      "enquiry_only": true,
      "is_visible": true,
      "is_published": true,
      "display_order": 13
    },
    {
      "name": "Comfy Mesh Chair",
      "slug": "comfy-mesh-chair",
      "category_slug": "seating",
      "subcategory": "Mesh Chair",
      "description": "Comfy ergonomic office chair featuring synchro-tilt mechanism, breathable mesh back, adjustable lumbar support, and heavy-duty nylon base.",
      "specifications": "Synchro-tilt mechanism, Class-4 Gas Lift, Breathable Korean Mesh, Nylon/Diecast Base.",
      "main_image": "images/archlabs/pages/page_17.png",
      "price": null,
      "display_price": false,
      "enquiry_only": true,
      "is_visible": true,
      "is_published": true,
      "display_order": 14
    },
    {
      "name": "Rio Mesh Chair",
      "slug": "rio-mesh-chair",
      "category_slug": "seating",
      "subcategory": "Mesh Chair",
      "description": "Rio ergonomic office chair featuring synchro-tilt mechanism, breathable mesh back, adjustable lumbar support, and heavy-duty nylon base.",
      "specifications": "Synchro-tilt mechanism, Class-4 Gas Lift, Breathable Korean Mesh, Nylon/Diecast Base.",
      "main_image": "images/archlabs/pages/page_18.png",
      "price": null,
      "display_price": false,
      "enquiry_only": true,
      "is_visible": true,
      "is_published": true,
      "display_order": 15
    },
    {
      "name": "Hilite Mesh Chair",
      "slug": "hilite-mesh-chair",
      "category_slug": "seating",
      "subcategory": "Mesh Chair",
      "description": "Hilite ergonomic office chair featuring synchro-tilt mechanism, breathable mesh back, adjustable lumbar support, and heavy-duty nylon base.",
      "specifications": "Synchro-tilt mechanism, Class-4 Gas Lift, Breathable Korean Mesh, Nylon/Diecast Base.",
      "main_image": "images/archlabs/pages/page_19.png",
      "price": null,
      "display_price": false,
      "enquiry_only": true,
      "is_visible": true,
      "is_published": true,
      "display_order": 16
    },
    {
      "name": "Ecco Mesh Chair",
      "slug": "ecco-mesh-chair",
      "category_slug": "seating",
      "subcategory": "Mesh Chair",
      "description": "Ecco ergonomic office chair featuring synchro-tilt mechanism, breathable mesh back, adjustable lumbar support, and heavy-duty nylon base.",
      "specifications": "Synchro-tilt mechanism, Class-4 Gas Lift, Breathable Korean Mesh, Nylon/Diecast Base.",
      "main_image": "images/archlabs/pages/page_20.png",
      "price": null,
      "display_price": false,
      "enquiry_only": true,
      "is_visible": true,
      "is_published": true,
      "display_order": 17
    },
    {
      "name": "Vento Mesh Chair",
      "slug": "vento-mesh-chair",
      "category_slug": "seating",
      "subcategory": "Mesh Chair",
      "description": "Vento ergonomic office chair featuring synchro-tilt mechanism, breathable mesh back, adjustable lumbar support, and heavy-duty nylon base.",
      "specifications": "Synchro-tilt mechanism, Class-4 Gas Lift, Breathable Korean Mesh, Nylon/Diecast Base.",
      "main_image": "images/archlabs/pages/page_21.png",
      "price": null,
      "display_price": false,
      "enquiry_only": true,
      "is_visible": true,
      "is_published": true,
      "display_order": 18
    },
    {
      "name": "Aura Mesh Chair",
      "slug": "aura-mesh-chair",
      "category_slug": "seating",
      "subcategory": "Mesh Chair",
      "description": "Aura ergonomic office chair featuring synchro-tilt mechanism, breathable mesh back, adjustable lumbar support, and heavy-duty nylon base.",
      "specifications": "Synchro-tilt mechanism, Class-4 Gas Lift, Breathable Korean Mesh, Nylon/Diecast Base.",
      "main_image": "images/archlabs/pages/page_22.png",
      "price": null,
      "display_price": false,
      "enquiry_only": true,
      "is_visible": true,
      "is_published": true,
      "display_order": 19
    },
    {
      "name": "Dynamic Mesh Chair",
      "slug": "dynamic-mesh-chair",
      "category_slug": "seating",
      "subcategory": "Mesh Chair",
      "description": "Dynamic ergonomic office chair featuring synchro-tilt mechanism, breathable mesh back, adjustable lumbar support, and heavy-duty nylon base.",
      "specifications": "Synchro-tilt mechanism, Class-4 Gas Lift, Breathable Korean Mesh, Nylon/Diecast Base.",
      "main_image": "images/archlabs/pages/page_23.png",
      "price": null,
      "display_price": false,
      "enquiry_only": true,
      "is_visible": true,
      "is_published": true,
      "display_order": 20
    },
    {
      "name": "Butterfly Mesh Chair",
      "slug": "butterfly-mesh-chair",
      "category_slug": "seating",
      "subcategory": "Mesh Chair",
      "description": "Butterfly ergonomic office chair featuring synchro-tilt mechanism, breathable mesh back, adjustable lumbar support, and heavy-duty nylon base.",
      "specifications": "Synchro-tilt mechanism, Class-4 Gas Lift, Breathable Korean Mesh, Nylon/Diecast Base.",
      "main_image": "images/archlabs/pages/page_24.png",
      "price": null,
      "display_price": false,
      "enquiry_only": true,
      "is_visible": true,
      "is_published": true,
      "display_order": 21
    },
    {
      "name": "Mystic Mesh Chair",
      "slug": "mystic-mesh-chair",
      "category_slug": "seating",
      "subcategory": "Mesh Chair",
      "description": "Mystic ergonomic office chair featuring synchro-tilt mechanism, breathable mesh back, adjustable lumbar support, and heavy-duty nylon base.",
      "specifications": "Synchro-tilt mechanism, Class-4 Gas Lift, Breathable Korean Mesh, Nylon/Diecast Base.",
      "main_image": "images/archlabs/pages/page_25.png",
      "price": null,
      "display_price": false,
      "enquiry_only": true,
      "is_visible": true,
      "is_published": true,
      "display_order": 22
    },
    {
      "name": "Breeze Mesh Chair",
      "slug": "breeze-mesh-chair",
      "category_slug": "seating",
      "subcategory": "Mesh Chair",
      "description": "Breeze ergonomic office chair featuring synchro-tilt mechanism, breathable mesh back, adjustable lumbar support, and heavy-duty nylon base.",
      "specifications": "Synchro-tilt mechanism, Class-4 Gas Lift, Breathable Korean Mesh, Nylon/Diecast Base.",
      "main_image": "images/archlabs/pages/page_26.png",
      "price": null,
      "display_price": false,
      "enquiry_only": true,
      "is_visible": true,
      "is_published": true,
      "display_order": 23
    },
    {
      "name": "Matrix 1 Mesh Chair",
      "slug": "matrix-1-mesh-chair",
      "category_slug": "seating",
      "subcategory": "Mesh Chair",
      "description": "Matrix 1 ergonomic office chair featuring synchro-tilt mechanism, breathable mesh back, adjustable lumbar support, and heavy-duty nylon base.",
      "specifications": "Synchro-tilt mechanism, Class-4 Gas Lift, Breathable Korean Mesh, Nylon/Diecast Base.",
      "main_image": "images/archlabs/pages/page_27.png",
      "price": null,
      "display_price": false,
      "enquiry_only": true,
      "is_visible": true,
      "is_published": true,
      "display_order": 24
    },
    {
      "name": "Marvel 1 & 2 Mesh Chair",
      "slug": "marvel-1-2-mesh-chair",
      "category_slug": "seating",
      "subcategory": "Mesh Chair",
      "description": "Marvel 1 & 2 ergonomic office chair featuring synchro-tilt mechanism, breathable mesh back, adjustable lumbar support, and heavy-duty nylon base.",
      "specifications": "Synchro-tilt mechanism, Class-4 Gas Lift, Breathable Korean Mesh, Nylon/Diecast Base.",
      "main_image": "images/archlabs/pages/page_28.png",
      "price": null,
      "display_price": false,
      "enquiry_only": true,
      "is_visible": true,
      "is_published": true,
      "display_order": 25
    },
    {
      "name": "Jazz Mesh Chair",
      "slug": "jazz-mesh-chair",
      "category_slug": "seating",
      "subcategory": "Mesh Chair",
      "description": "Jazz ergonomic office chair featuring synchro-tilt mechanism, breathable mesh back, adjustable lumbar support, and heavy-duty nylon base.",
      "specifications": "Synchro-tilt mechanism, Class-4 Gas Lift, Breathable Korean Mesh, Nylon/Diecast Base.",
      "main_image": "images/archlabs/pages/page_29.png",
      "price": null,
      "display_price": false,
      "enquiry_only": true,
      "is_visible": true,
      "is_published": true,
      "display_order": 26
    },
    {
      "name": "Flash Mesh Chair",
      "slug": "flash-mesh-chair",
      "category_slug": "seating",
      "subcategory": "Mesh Chair",
      "description": "Flash ergonomic office chair featuring synchro-tilt mechanism, breathable mesh back, adjustable lumbar support, and heavy-duty nylon base.",
      "specifications": "Synchro-tilt mechanism, Class-4 Gas Lift, Breathable Korean Mesh, Nylon/Diecast Base.",
      "main_image": "images/archlabs/pages/page_30.png",
      "price": null,
      "display_price": false,
      "enquiry_only": true,
      "is_visible": true,
      "is_published": true,
      "display_order": 27
    },
    {
      "name": "Bonai Mesh Chair",
      "slug": "bonai-mesh-chair",
      "category_slug": "seating",
      "subcategory": "Mesh Chair",
      "description": "Bonai ergonomic office chair featuring synchro-tilt mechanism, breathable mesh back, adjustable lumbar support, and heavy-duty nylon base.",
      "specifications": "Synchro-tilt mechanism, Class-4 Gas Lift, Breathable Korean Mesh, Nylon/Diecast Base.",
      "main_image": "images/archlabs/pages/page_31.png",
      "price": null,
      "display_price": false,
      "enquiry_only": true,
      "is_visible": true,
      "is_published": true,
      "display_order": 28
    },
    {
      "name": "X Mesh Mesh Chair",
      "slug": "x-mesh-mesh-chair",
      "category_slug": "seating",
      "subcategory": "Mesh Chair",
      "description": "X Mesh ergonomic office chair featuring synchro-tilt mechanism, breathable mesh back, adjustable lumbar support, and heavy-duty nylon base.",
      "specifications": "Synchro-tilt mechanism, Class-4 Gas Lift, Breathable Korean Mesh, Nylon/Diecast Base.",
      "main_image": "images/archlabs/pages/page_32.png",
      "price": null,
      "display_price": false,
      "enquiry_only": true,
      "is_visible": true,
      "is_published": true,
      "display_order": 29
    },
    {
      "name": "Spenser Mesh Chair",
      "slug": "spenser-mesh-chair",
      "category_slug": "seating",
      "subcategory": "Mesh Chair",
      "description": "Spenser ergonomic office chair featuring synchro-tilt mechanism, breathable mesh back, adjustable lumbar support, and heavy-duty nylon base.",
      "specifications": "Synchro-tilt mechanism, Class-4 Gas Lift, Breathable Korean Mesh, Nylon/Diecast Base.",
      "main_image": "images/archlabs/pages/page_33.png",
      "price": null,
      "display_price": false,
      "enquiry_only": true,
      "is_visible": true,
      "is_published": true,
      "display_order": 30
    },
    {
      "name": "Luxe Leather Chair",
      "slug": "luxe-leather-chair",
      "category_slug": "seating",
      "subcategory": "Leather Chair",
      "description": "Luxe executive leather chair with top-grain leather upholstery, deep cushioning, and polished aluminium armrests.",
      "specifications": "Top-grain Genuine Leather, Knee-Tilt Lock Mechanism, Polished Diecast Aluminium Base.",
      "main_image": "images/archlabs/pages/page_36.png",
      "price": null,
      "display_price": false,
      "enquiry_only": true,
      "is_visible": true,
      "is_published": true,
      "display_order": 31
    },
    {
      "name": "Elara Leather Chair",
      "slug": "elara-leather-chair",
      "category_slug": "seating",
      "subcategory": "Leather Chair",
      "description": "Elara executive leather chair with top-grain leather upholstery, deep cushioning, and polished aluminium armrests.",
      "specifications": "Top-grain Genuine Leather, Knee-Tilt Lock Mechanism, Polished Diecast Aluminium Base.",
      "main_image": "images/archlabs/pages/page_37.png",
      "price": null,
      "display_price": false,
      "enquiry_only": true,
      "is_visible": true,
      "is_published": true,
      "display_order": 32
    },
    {
      "name": "Regent Leather Chair",
      "slug": "regent-leather-chair",
      "category_slug": "seating",
      "subcategory": "Leather Chair",
      "description": "Regent executive leather chair with top-grain leather upholstery, deep cushioning, and polished aluminium armrests.",
      "specifications": "Top-grain Genuine Leather, Knee-Tilt Lock Mechanism, Polished Diecast Aluminium Base.",
      "main_image": "images/archlabs/pages/page_38.png",
      "price": null,
      "display_price": false,
      "enquiry_only": true,
      "is_visible": true,
      "is_published": true,
      "display_order": 33
    },
    {
      "name": "Forma Leather Chair",
      "slug": "forma-leather-chair",
      "category_slug": "seating",
      "subcategory": "Leather Chair",
      "description": "Forma executive leather chair with top-grain leather upholstery, deep cushioning, and polished aluminium armrests.",
      "specifications": "Top-grain Genuine Leather, Knee-Tilt Lock Mechanism, Polished Diecast Aluminium Base.",
      "main_image": "images/archlabs/pages/page_39.png",
      "price": null,
      "display_price": false,
      "enquiry_only": true,
      "is_visible": true,
      "is_published": true,
      "display_order": 34
    },
    {
      "name": "Nero Leather Chair",
      "slug": "nero-leather-chair",
      "category_slug": "seating",
      "subcategory": "Leather Chair",
      "description": "Nero executive leather chair with top-grain leather upholstery, deep cushioning, and polished aluminium armrests.",
      "specifications": "Top-grain Genuine Leather, Knee-Tilt Lock Mechanism, Polished Diecast Aluminium Base.",
      "main_image": "images/archlabs/pages/page_40.png",
      "price": null,
      "display_price": false,
      "enquiry_only": true,
      "is_visible": true,
      "is_published": true,
      "display_order": 35
    },
    {
      "name": "Arc Standard Chair",
      "slug": "arc-standard-chair",
      "category_slug": "seating",
      "subcategory": "Training Chair",
      "description": "Arc Standard training chair engineered for seminars, classrooms, and corporate learning centers.",
      "specifications": "Stackable steel frame, optional foldable writing tablet, high-density foam seat.",
      "main_image": "images/archlabs/pages/page_42.png",
      "price": null,
      "display_price": false,
      "enquiry_only": true,
      "is_visible": true,
      "is_published": true,
      "display_order": 36
    },
    {
      "name": "Cove Cushioned Chair",
      "slug": "cove-cushioned-chair",
      "category_slug": "seating",
      "subcategory": "Training Chair",
      "description": "Cove Cushioned training chair engineered for seminars, classrooms, and corporate learning centers.",
      "specifications": "Stackable steel frame, optional foldable writing tablet, high-density foam seat.",
      "main_image": "images/archlabs/pages/page_43.png",
      "price": null,
      "display_price": false,
      "enquiry_only": true,
      "is_visible": true,
      "is_published": true,
      "display_order": 37
    },
    {
      "name": "Pivot Writing Table Chair",
      "slug": "pivot-writing-table-chair",
      "category_slug": "seating",
      "subcategory": "Training Chair",
      "description": "Pivot Writing Table training chair engineered for seminars, classrooms, and corporate learning centers.",
      "specifications": "Stackable steel frame, optional foldable writing tablet, high-density foam seat.",
      "main_image": "images/archlabs/pages/page_44.png",
      "price": null,
      "display_price": false,
      "enquiry_only": true,
      "is_visible": true,
      "is_published": true,
      "display_order": 38
    },
    {
      "name": "Pivot Full Writing Table Chair",
      "slug": "pivot-full-writing-table-chair",
      "category_slug": "seating",
      "subcategory": "Training Chair",
      "description": "Pivot Full Writing Table training chair engineered for seminars, classrooms, and corporate learning centers.",
      "specifications": "Stackable steel frame, optional foldable writing tablet, high-density foam seat.",
      "main_image": "images/archlabs/pages/page_45.png",
      "price": null,
      "display_price": false,
      "enquiry_only": true,
      "is_visible": true,
      "is_published": true,
      "display_order": 39
    },
    {
      "name": "Stack Storage Variants Chair",
      "slug": "stack-storage-variants-chair",
      "category_slug": "seating",
      "subcategory": "Training Chair",
      "description": "Stack Storage Variants training chair engineered for seminars, classrooms, and corporate learning centers.",
      "specifications": "Stackable steel frame, optional foldable writing tablet, high-density foam seat.",
      "main_image": "images/archlabs/pages/page_46.png",
      "price": null,
      "display_price": false,
      "enquiry_only": true,
      "is_visible": true,
      "is_published": true,
      "display_order": 40
    },
    {
      "name": "ArchTwin Chair",
      "slug": "archtwin-chair",
      "category_slug": "seating",
      "subcategory": "Training Chair",
      "description": "ArchTwin training chair engineered for seminars, classrooms, and corporate learning centers.",
      "specifications": "Stackable steel frame, optional foldable writing tablet, high-density foam seat.",
      "main_image": "images/archlabs/pages/page_47.png",
      "price": null,
      "display_price": false,
      "enquiry_only": true,
      "is_visible": true,
      "is_published": true,
      "display_order": 41
    },
    {
      "name": "ArchTwin Flip-Up Table Chair",
      "slug": "archtwin-flip-up-table-chair",
      "category_slug": "seating",
      "subcategory": "Training Chair",
      "description": "ArchTwin Flip-Up Table training chair engineered for seminars, classrooms, and corporate learning centers.",
      "specifications": "Stackable steel frame, optional foldable writing tablet, high-density foam seat.",
      "main_image": "images/archlabs/pages/page_48.png",
      "price": null,
      "display_price": false,
      "enquiry_only": true,
      "is_visible": true,
      "is_published": true,
      "display_order": 42
    },
    {
      "name": "Metro Linea 2 Seater",
      "slug": "metro-linea-2-seater",
      "category_slug": "soft-seating",
      "subcategory": "Lounge",
      "description": "Metro Linea 2 Seater heavy-duty perforated steel beam seating for airports, waiting rooms, and public lobbies.",
      "specifications": "Perforated steel seats, chrome plated beam legs, anti-skid rubber feet.",
      "main_image": "images/archlabs/pages/page_50.png",
      "price": null,
      "display_price": false,
      "enquiry_only": true,
      "is_visible": true,
      "is_published": true,
      "display_order": 43
    },
    {
      "name": "Metro Linea 3 Seater",
      "slug": "metro-linea-3-seater",
      "category_slug": "soft-seating",
      "subcategory": "Lounge",
      "description": "Metro Linea 3 Seater heavy-duty perforated steel beam seating for airports, waiting rooms, and public lobbies.",
      "specifications": "Perforated steel seats, chrome plated beam legs, anti-skid rubber feet.",
      "main_image": "images/archlabs/pages/page_51.png",
      "price": null,
      "display_price": false,
      "enquiry_only": true,
      "is_visible": true,
      "is_published": true,
      "display_order": 44
    },
    {
      "name": "Metro Linea 5 Seater",
      "slug": "metro-linea-5-seater",
      "category_slug": "soft-seating",
      "subcategory": "Lounge",
      "description": "Metro Linea 5 Seater heavy-duty perforated steel beam seating for airports, waiting rooms, and public lobbies.",
      "specifications": "Perforated steel seats, chrome plated beam legs, anti-skid rubber feet.",
      "main_image": "images/archlabs/pages/page_52.png",
      "price": null,
      "display_price": false,
      "enquiry_only": true,
      "is_visible": true,
      "is_published": true,
      "display_order": 45
    },
    {
      "name": "AC01 Stack Chair",
      "slug": "ac01-stack-chair",
      "category_slug": "seating",
      "subcategory": "Cafe Chair",
      "description": "AC01 Stack Chair modern cafeteria chair designed for corporate pantries, food courts, and dining halls.",
      "specifications": "Polypropylene moulded shell / bentwood timber frame, chrome steel legs.",
      "main_image": "images/archlabs/pages/page_54.png",
      "price": null,
      "display_price": false,
      "enquiry_only": true,
      "is_visible": true,
      "is_published": true,
      "display_order": 46
    },
    {
      "name": "AC02 Curve Chair",
      "slug": "ac02-curve-chair",
      "category_slug": "seating",
      "subcategory": "Cafe Chair",
      "description": "AC02 Curve Chair modern cafeteria chair designed for corporate pantries, food courts, and dining halls.",
      "specifications": "Polypropylene moulded shell / bentwood timber frame, chrome steel legs.",
      "main_image": "images/archlabs/pages/page_55.png",
      "price": null,
      "display_price": false,
      "enquiry_only": true,
      "is_visible": true,
      "is_published": true,
      "display_order": 47
    },
    {
      "name": "AC03 Arc Chair",
      "slug": "ac03-arc-chair",
      "category_slug": "seating",
      "subcategory": "Cafe Chair",
      "description": "AC03 Arc Chair modern cafeteria chair designed for corporate pantries, food courts, and dining halls.",
      "specifications": "Polypropylene moulded shell / bentwood timber frame, chrome steel legs.",
      "main_image": "images/archlabs/pages/page_56.png",
      "price": null,
      "display_price": false,
      "enquiry_only": true,
      "is_visible": true,
      "is_published": true,
      "display_order": 48
    },
    {
      "name": "AC04 Spindle Chair",
      "slug": "ac04-spindle-chair",
      "category_slug": "seating",
      "subcategory": "Cafe Chair",
      "description": "AC04 Spindle Chair modern cafeteria chair designed for corporate pantries, food courts, and dining halls.",
      "specifications": "Polypropylene moulded shell / bentwood timber frame, chrome steel legs.",
      "main_image": "images/archlabs/pages/page_57.png",
      "price": null,
      "display_price": false,
      "enquiry_only": true,
      "is_visible": true,
      "is_published": true,
      "display_order": 49
    },
    {
      "name": "AC06 Timber Chair",
      "slug": "ac06-timber-chair",
      "category_slug": "seating",
      "subcategory": "Cafe Chair",
      "description": "AC06 Timber Chair modern cafeteria chair designed for corporate pantries, food courts, and dining halls.",
      "specifications": "Polypropylene moulded shell / bentwood timber frame, chrome steel legs.",
      "main_image": "images/archlabs/pages/page_58.png",
      "price": null,
      "display_price": false,
      "enquiry_only": true,
      "is_visible": true,
      "is_published": true,
      "display_order": 50
    },
    {
      "name": "AC07 Lounge Chair",
      "slug": "ac07-lounge-chair",
      "category_slug": "seating",
      "subcategory": "Cafe Chair",
      "description": "AC07 Lounge Chair modern cafeteria chair designed for corporate pantries, food courts, and dining halls.",
      "specifications": "Polypropylene moulded shell / bentwood timber frame, chrome steel legs.",
      "main_image": "images/archlabs/pages/page_59.png",
      "price": null,
      "display_price": false,
      "enquiry_only": true,
      "is_visible": true,
      "is_published": true,
      "display_order": 51
    },
    {
      "name": "AC08 Crest Chair",
      "slug": "ac08-crest-chair",
      "category_slug": "seating",
      "subcategory": "Cafe Chair",
      "description": "AC08 Crest Chair modern cafeteria chair designed for corporate pantries, food courts, and dining halls.",
      "specifications": "Polypropylene moulded shell / bentwood timber frame, chrome steel legs.",
      "main_image": "images/archlabs/pages/page_60.png",
      "price": null,
      "display_price": false,
      "enquiry_only": true,
      "is_visible": true,
      "is_published": true,
      "display_order": 52
    },
    {
      "name": "Model HA-01 Sit-Stand Executive Desk",
      "slug": "model-ha-01-sit-stand-executive-desk",
      "category_slug": "workstations",
      "subcategory": "Height Adjustable Series",
      "description": "Motorized dual-motor sit-to-stand executive desk with digital height preset controller and wire raceway.",
      "specifications": "Commercial grade materials, BIFMA certified hardware, 5-year warranty.",
      "main_image": "images/categories/cat_workstations.jpg",
      "price": null,
      "display_price": false,
      "enquiry_only": true,
      "is_visible": true,
      "is_published": true,
      "display_order": 53
    },
    {
      "name": "Model HA-02 Back-to-Back Bench System",
      "slug": "model-ha-02-back-to-back-bench-system",
      "category_slug": "workstations",
      "subcategory": "Height Adjustable Series",
      "description": "4-person electric height-adjustable back-to-back benching system with acoustic fabric divider screens.",
      "specifications": "Commercial grade materials, BIFMA certified hardware, 5-year warranty.",
      "main_image": "images/categories/cat_workstations.jpg",
      "price": null,
      "display_price": false,
      "enquiry_only": true,
      "is_visible": true,
      "is_published": true,
      "display_order": 54
    },
    {
      "name": "Model HA-03 Corner L-Desk Managerial",
      "slug": "model-ha-03-corner-l-desk-managerial",
      "category_slug": "workstations",
      "subcategory": "Height Adjustable Series",
      "description": "L-shaped motorized height-adjustable desk with integrated side return storage credenza.",
      "specifications": "Commercial grade materials, BIFMA certified hardware, 5-year warranty.",
      "main_image": "images/categories/cat_workstations.jpg",
      "price": null,
      "display_price": false,
      "enquiry_only": true,
      "is_visible": true,
      "is_published": true,
      "display_order": 55
    },
    {
      "name": "Model DS-Linear 4-Person Cluster",
      "slug": "model-ds-linear-4-person-cluster",
      "category_slug": "workstations",
      "subcategory": "Desking Series",
      "description": "Linear open-plan 4-person workstation cluster with steel loop leg frame and desktop power boxes.",
      "specifications": "Commercial grade materials, BIFMA certified hardware, 5-year warranty.",
      "main_image": "images/categories/cat_workstations.jpg",
      "price": null,
      "display_price": false,
      "enquiry_only": true,
      "is_visible": true,
      "is_published": true,
      "display_order": 56
    },
    {
      "name": "Model DS-Loop Leg 2-Person Bench",
      "slug": "model-ds-loop-leg-2-person-bench",
      "category_slug": "workstations",
      "subcategory": "Desking Series",
      "description": "2-person back-to-back desking bench with powder-coated triangular leg profile.",
      "specifications": "Commercial grade materials, BIFMA certified hardware, 5-year warranty.",
      "main_image": "images/categories/cat_workstations.jpg",
      "price": null,
      "display_price": false,
      "enquiry_only": true,
      "is_visible": true,
      "is_published": true,
      "display_order": 57
    },
    {
      "name": "Model PS-60mm Tile Partition System",
      "slug": "model-ps-60mm-tile-partition-system",
      "category_slug": "workstations",
      "subcategory": "Panel Series",
      "description": "60mm thick tile-based partition system with fabric tackable panels, whiteboards, and raceway wire channels.",
      "specifications": "Commercial grade materials, BIFMA certified hardware, 5-year warranty.",
      "main_image": "images/categories/cat_workstations.jpg",
      "price": null,
      "display_price": false,
      "enquiry_only": true,
      "is_visible": true,
      "is_published": true,
      "display_order": 58
    },
    {
      "name": "Model CB-Executive Director Desk",
      "slug": "model-cb-executive-director-desk",
      "category_slug": "tables",
      "subcategory": "Cabin Tables",
      "description": "Premium teak veneer executive director desk featuring leatherette desk pad and integrated runner cabinet.",
      "specifications": "Commercial grade materials, BIFMA certified hardware, 5-year warranty.",
      "main_image": "images/categories/cat_tables.png",
      "price": null,
      "display_price": false,
      "enquiry_only": true,
      "is_visible": true,
      "is_published": true,
      "display_order": 59
    },
    {
      "name": "Model CB-Managerial Side Return Desk",
      "slug": "model-cb-managerial-side-return-desk",
      "category_slug": "tables",
      "subcategory": "Cabin Tables",
      "description": "Managerial L-desk with modesty panel, pedestal drawers, and side runner unit.",
      "specifications": "Commercial grade materials, BIFMA certified hardware, 5-year warranty.",
      "main_image": "images/categories/cat_tables.png",
      "price": null,
      "display_price": false,
      "enquiry_only": true,
      "is_visible": true,
      "is_published": true,
      "display_order": 60
    },
    {
      "name": "Model MT-12 Seater Boardroom Table",
      "slug": "model-mt-12-seater-boardroom-table",
      "category_slug": "tables",
      "subcategory": "Meeting Tables",
      "description": "12-seater conference boardroom table with pop-up HDMI/LAN/Power connectivity modules.",
      "specifications": "Commercial grade materials, BIFMA certified hardware, 5-year warranty.",
      "main_image": "images/categories/cat_tables.png",
      "price": null,
      "display_price": false,
      "enquiry_only": true,
      "is_visible": true,
      "is_published": true,
      "display_order": 61
    },
    {
      "name": "Model ST-Mobile Pedestal (3 Drawer)",
      "slug": "model-st-mobile-pedestal-3-drawer-",
      "category_slug": "storage",
      "subcategory": "Prelam Storage",
      "description": "3-drawer mobile under-desk pedestal with central lock, anti-tilt castor, and stationery tray.",
      "specifications": "Commercial grade materials, BIFMA certified hardware, 5-year warranty.",
      "main_image": "images/categories/cat_storage.png",
      "price": null,
      "display_price": false,
      "enquiry_only": true,
      "is_visible": true,
      "is_published": true,
      "display_order": 62
    },
    {
      "name": "Model PD-Solo Acoustic Telephone Booth",
      "slug": "model-pd-solo-acoustic-telephone-booth",
      "category_slug": "pods",
      "subcategory": null,
      "description": "Sound-insulated solo acoustic phone pod equipped with silent ventilation fan, LED lighting, and power outlets.",
      "specifications": "Commercial grade materials, BIFMA certified hardware, 5-year warranty.",
      "main_image": "images/categories/cat_pods.jpg",
      "price": null,
      "display_price": false,
      "enquiry_only": true,
      "is_visible": true,
      "is_published": true,
      "display_order": 63
    },
    {
      "name": "Model CP-Acoustic Nylon Modular Tile",
      "slug": "model-cp-acoustic-nylon-modular-tile",
      "category_slug": "carpets",
      "subcategory": null,
      "description": "High-performance modular carpet tiles with sound-absorbing recycled cushion backing.",
      "specifications": "Commercial grade materials, BIFMA certified hardware, 5-year warranty.",
      "main_image": "images/categories/cat_carpets.jpg",
      "price": null,
      "display_price": false,
      "enquiry_only": true,
      "is_visible": true,
      "is_published": true,
      "display_order": 64
    },
    {
      "name": "Model OD-Synthetic Wicker Terrace Lounge",
      "slug": "model-od-synthetic-wicker-terrace-lounge",
      "category_slug": "outdoor",
      "subcategory": null,
      "description": "Weather-resistant synthetic wicker terrace lounge set with UV-protected outdoor cushions.",
      "specifications": "Commercial grade materials, BIFMA certified hardware, 5-year warranty.",
      "main_image": "images/categories/cat_outdoor.jpg",
      "price": null,
      "display_price": false,
      "enquiry_only": true,
      "is_visible": true,
      "is_published": true,
      "display_order": 65
    },
    {
      "name": "Model ED-Single Student Ergonomic Desk",
      "slug": "model-ed-single-student-ergonomic-desk",
      "category_slug": "educational",
      "subcategory": "Classroom",
      "description": "Ergonomic classroom desk & chair combo with book bag hook and wire storage rack.",
      "specifications": "Commercial grade materials, BIFMA certified hardware, 5-year warranty.",
      "main_image": "images/categories/cat_education.png",
      "price": null,
      "display_price": false,
      "enquiry_only": true,
      "is_visible": true,
      "is_published": true,
      "display_order": 66
    },
    {
      "name": "Model AC-Gas Spring Dual Monitor Arm",
      "slug": "model-ac-gas-spring-dual-monitor-arm",
      "category_slug": "storage",
      "subcategory": "Metal Storage",
      "description": "Full-motion dual monitor gas spring arm with desk clamp and integrated cable management clips.",
      "specifications": "Commercial grade materials, BIFMA certified hardware, 5-year warranty.",
      "main_image": "images/categories/cat_tables.png",
      "price": null,
      "display_price": false,
      "enquiry_only": true,
      "is_visible": true,
      "is_published": true,
      "display_order": 67
    },
    {
      "name": "Executive Lounge Armchairs",
      "slug": "executive-lounge-armchairs",
      "category_slug": "soft-seating",
      "subcategory": "Lounge",
      "description": "Single-seat ergonomic lounge armchairs in premium leather or acoustic fabric upholstery.",
      "specifications": "High resilience foam, premium fabric / leatherette, hardwood frame.",
      "main_image": "images/categories/cat_soft_seating.jpg",
      "price": null,
      "display_price": false,
      "enquiry_only": true,
      "is_visible": true,
      "is_published": true,
      "display_order": 68
    },
    {
      "name": "2 & 3-Seater Executive Sofas",
      "slug": "2-3-seater-executive-sofas",
      "category_slug": "soft-seating",
      "subcategory": "Lounge",
      "description": "Sleek multi-seater reception couches featuring high-resilience foam cushioning.",
      "specifications": "High resilience foam, premium fabric / leatherette, hardwood frame.",
      "main_image": "images/collection/collection-1.jpg",
      "price": null,
      "display_price": false,
      "enquiry_only": true,
      "is_visible": true,
      "is_published": true,
      "display_order": 69
    },
    {
      "name": "Collaborative Booth Seating",
      "slug": "collaborative-booth-seating",
      "category_slug": "soft-seating",
      "subcategory": "Collaborative",
      "description": "High-back sound dampening collaborative booths creating semi-private discussion nooks.",
      "specifications": "High resilience foam, premium fabric / leatherette, hardwood frame.",
      "main_image": "images/collection/collection-2.jpg",
      "price": null,
      "display_price": false,
      "enquiry_only": true,
      "is_visible": true,
      "is_published": true,
      "display_order": 70
    },
    {
      "name": "Geometrical Pouffes & Ottomans",
      "slug": "geometrical-pouffes-ottomans",
      "category_slug": "soft-seating",
      "subcategory": "Pouffe",
      "description": "Flexible circular, hexagonal, and square soft pouffes for breakout areas.",
      "specifications": "High resilience foam, premium fabric / leatherette, hardwood frame.",
      "main_image": "images/sections/s-lookbook-1.jpg",
      "price": null,
      "display_price": false,
      "enquiry_only": true,
      "is_visible": true,
      "is_published": true,
      "display_order": 71
    },
    {
      "name": "Occasional Center Tables",
      "slug": "occasional-center-tables",
      "category_slug": "soft-seating",
      "subcategory": "Occasional Tables",
      "description": "Designer low-height coffee tables with veneered wood or marble tops.",
      "specifications": "High resilience foam, premium fabric / leatherette, hardwood frame.",
      "main_image": "images/categories/cat_tables.png",
      "price": null,
      "display_price": false,
      "enquiry_only": true,
      "is_visible": true,
      "is_published": true,
      "display_order": 72
    }
  ],
  "hero_sections": [
    {
      "heading": "Transforming Workspaces.<br><span class=\"text-gradient-red\">Elevating Possibilities.</span>",
      "description": "Premium office furniture, interior systems, and turnkey workspace solutions designed for modern corporate businesses, MNCs, educational institutions, and professional environments.",
      "slide_1": "images/sections/hero-slide-1.png",
      "slide_2": "images/sections/hero-slide-2.png",
      "slide_3": "images/sections/hero-slide-3.png",
      "background_image": "images/sections/hero-slide-1.png",
      "is_custom_updated": false
    }
  ],
  "about_sections": [
    {
      "title": "Creating Workspaces That Work for You",
      "main_description": "At Vishista Office Solutions Pvt Ltd, we specialize in delivering world-class workspace environments.",
      "is_custom_updated": false
    }
  ],
  "footer_content": [
    {
      "company_description": "Vishista Office Solutions Pvt Ltd is a premier provider of corporate office furniture and turnkey workspace interior solutions.",
      "address": "Plot No 45, Jubilee Hills, Road No 36, Hyderabad, Telangana 500033",
      "phone": "+91 98490 12345",
      "email": "info@vishista.com"
    }
  ],
  "projects": [
    {
      "name": "Corporate Tech Hub",
      "slug": "corporate-tech-hub",
      "client": "MNC Tech Firm, Hitec City",
      "category": "Turnkey Workspace",
      "location": "Hyderabad, Telangana",
      "description": "500-seater modular workstation installation with acoustic panel partitions and executive director cabins.",
      "image_url": "images/sections/hero-slide-1.png",
      "completion_year": "2025",
      "is_visible": true,
      "is_published": true,
      "display_order": 1
    },
    {
      "name": "Financial Services Regional HQ",
      "slug": "financial-services-hq",
      "client": "Leading Financial Institution",
      "category": "Executive Seating & Desks",
      "location": "Gachibowli, Hyderabad",
      "description": "Executive ArchLabs leather seating, high-density compactor storage, and 20-seater boardroom meeting tables.",
      "image_url": "images/sections/hero-slide-2.png",
      "completion_year": "2025",
      "is_visible": true,
      "is_published": true,
      "display_order": 2
    },
    {
      "name": "Global R&D Center",
      "slug": "global-rd-center",
      "client": "Pharma & Biotech Enterprise",
      "category": "Acoustic Pods & Soft Seating",
      "location": "Genome Valley, Hyderabad",
      "description": "Soundproof acoustic meeting pods, collaborative lounge sofa booths, and interface carpet tile flooring.",
      "image_url": "images/sections/hero-slide-3.png",
      "completion_year": "2024",
      "is_visible": true,
      "is_published": true,
      "display_order": 3
    }
  ]
};

if (typeof window !== 'undefined') {
    window.SUPABASE_URL = SUPABASE_URL;
    window.SUPABASE_ANON_KEY = SUPABASE_ANON_KEY;
    window.CLOUDINARY_CLOUD_NAME = CLOUDINARY_CLOUD_NAME;
    window.CLOUDINARY_UPLOAD_PRESET = CLOUDINARY_UPLOAD_PRESET;
    window.VISHISTA_SEED_DATA = VISHISTA_SEED_DATA;
    window.supabaseClient = supabaseClient;
    window.uploadToCloudinary = uploadToCloudinary;
    window.CMSDataStore = CMSDataStore;
}
